"""Adaugare coloana parola

Revision ID: 18bc79d69e4f
Revises: 49d276df09f7
Create Date: 2022-05-18 13:52:40.156280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bc79d69e4f'
down_revision = '49d276df09f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pass_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pass_hash')
    # ### end Alembic commands ###
